### ISSUE TITLE
Continues to show yellow warning squiggly line

### ISSUE THREAD

**Issue by jonreid** [seanhenry/TearDownGenerator#1]
Sean,
First, thanks for updating this, my all-time favorite AppCode plugin! What a relief to have it back.

I'm used to the yellow warning line on the test class appearing when a class is missing a tearDown of anything in the test fixture. But in the latest version, the warning line remains after generating tearDown.

**Comment by seanhenry** [comment]
Hi Jon,

Thanks for raising this issue. I'm pleased you're getting good use out of it!

I've taken a look and it seems like it's still working in 2019.3.6 but has broken in 2020.1 EAP. I've fixed the issue and uploaded it to JetBrains but it will take a little while to become available so in the meantime you can manually install it by downloading it from the [releases page](https://github.com/seanhenry/TearDownGenerator/releases). 

Thanks for the early warning!

**Comment by jonreid** [comment]
YAY YAY
